# Changes here will be overwritten by Copier
_commit: 22b3cb1
_src_path: gh:maxlansky1/projectTemplate
author_email: dick@gmail.com
author_name: Иван Иванов
project_name: copier-test
project_summary: Это проект copier-test
